project:
  type: website
  output-dir: docs
  resources:
    - "CV_Julia_Pereira.pdf"

website:
  title: "Julia Maria Pereira"
  favicon: favicon.svg
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: experience.qmd
        text: Experience
      - href: research.qmd
        text: Research
      - href: skills.qmd
        text: Skills
      - href: writing.qmd
        text: Writing Samples
      - href: contact.qmd
        text: Contact
    right:
      - href: https://github.com/juliamariap
        text: "GitHub"
        icon: github

format:
  html:
    theme:
      - cosmo
      - brand.scss
    css: styles.css
    toc: true
